### ISSUE TITLE
Roadmap first draft

### ISSUE THREAD

**Issue by AugustinMauroy** [scholarsuite/scholarsuite.github.io#1]
Here's the roadmap for a small project website

- [x] Setup [next.js](https://nextjs.org) app
  - [x] i18n with [`next-int`](https://next-intl-docs.vercel.app)
  - [x] Landing page that describe the project
  - [x] Lint/format => [ESlint](https://eslint.org) + [prettier](https://prettier.io) or [biomejs](https://biomejs.dev)
  - [x] ~~Unit test with [node test-runner]() and [`nodejs-loaders`](https://github.com/JakobJingleheimer/nodejs-loaders)~~
- [x] Setup GitHub things
  - [x] Setup [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)
  - [x] PR template + ~~issue template~~ [doc](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)
  - [x] GA action
    - [x] PR+main: Lint/format + test
    - [x] main: publish to GitHub page
